### ISSUE TITLE
minor issue, probably in watch-only wallet

### ISSUE THREAD

**Issue by molecular** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#18]
version 1.2

just thought I'd leave this here...

```
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/lib/plugins.py", line 521, in run_hook
    r = f(*args)
  File "/home/nick/.electron-cash/external_plugins/inter-wallet-transfer-v1.2.zip/inter-wallet-transfer/qt.py", line 70, in load_wallet
    self.add_ui_for_wallet(wallet_name, window)
  File "/home/nick/.electron-cash/external_plugins/inter-wallet-transfer-v1.2.zip/inter-wallet-transfer/qt.py", line 93, in add_ui_for_wallet
    l = LoadRWallet(window, self, wallet_name)
  File "/home/nick/.electron-cash/external_plugins/inter-wallet-transfer-v1.2.zip/inter-wallet-transfer/ui.py", line 46, in __init__
    l2 = QLabel(self.local_xpub[0])
IndexError: list index out of range
```

**Comment by KarolTrzeszczkowski** [comment]
Thanks for reporting, it is single address watch only, am I right?

**Comment by molecular** [comment]
> it is single address watch only, am I right?

nope, multiple addresses, but imported as list (using wallet -> import addresses), not based on xpub.

**Comment by KarolTrzeszczkowski** [comment]
Thanks for reporting it.
